spring:
  application:
    name: price-watch

# postgresql configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/price_watch
    username: postgres
    password: password1!

# jpa & hibernate tunning
  jpa:
    hibernate:
      ddl-auto: validate

# flyway configuration
  flyway:
    enabled: true
    baseline-on-migrate: true